name: persister
description: Persister allows you to increase your performance when using MySql on dart servers, providing an easy API.
version: 1.0.4
homepage: https://github.com/raul94a/persister

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  mysql_manager: ^1.0.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
